### ISSUE TITLE
Netlify build errors

### ISSUE THREAD

**Issue by wildpow** [mdreizin/gatsby-plugin-robots-txt#457] opened 2021-05-27 15:22 UTC
Resently upgraded `gatsby-plugin-robots-txt` from 1.5.5 to 1.6.2 and I am getting this Netlify build error:
```
7:56:33 AM: error "gatsby-plugin-robots-txt" threw an error while running the onPostBuild lifecycle:
7:56:33 AM: Cannot read property 'startsWith' of null
7:56:33 AM:   78 |       new URL(mergedOptions.sitemap)
7:56:33 AM:   79 |     } catch {
7:56:33 AM: > 80 |       mergedOptions.sitemap = new URL(mergedOptions.sitemap.startsWith(pathPrefix) ? mergedOptions.sitemap : path.posix.join(pathPrefix, mergedOptions.sitemap), mergedOptions.host).toString()
7:56:33 AM:      |                                                             ^
7:56:33 AM:   81 |     }
7:56:33 AM:   82 |   }
7:56:33 AM:   83 |
```
My config is a one-to-one copy of the Netlify example in the docs. Went back to 1.5.6 and everything is fine. I'm assuming it has something to do with the changes in [#441](https://github.com/mdreizin/gatsby-plugin-robots-txt/pull/441) and the docs just need to be updated with a new elimination.

**Comment by laurenskling** [comment] 2021-05-27 18:12
duplicate of https://github.com/mdreizin/gatsby-plugin-robots-txt/issues/451

**Comment by ajmalafif** [comment] 2021-05-28 09:46
@wildpow hey do you solve this by going back to `1.5.6` for now? Or is there a workaround?

**Comment by wildpow** [comment] 2021-05-28 15:31
@ajmalafif Yeah, going back to `1.5.6` worked for me.

Not sure if any of these steps made a difference besides the first but, this is exactly what I did when downgrading this plug-in:
1. `npm i gatsby-plugin-robots-txt@1.5.6`
2. Disabled Gatsby cache plug-in.
3. After pushing this change I cleared Netlify cache before build.

**Comment by ajmalafif** [comment] 2021-05-28 16:31
@wildpow thanks for the step-by-step help for this! 

I think it‘s because I don‘t know how to do `2. Disabled Gatsby cache plug-in.` which is why I think even though I‘m on `1.5.6` I still get the error

**Comment by wildpow** [comment] 2021-05-30 04:50
@ajmalafif Glad you got it working 😀

**Comment by jonathanphz** [comment] 2021-07-27 15:07
Latest merge was suppose to fix this but is not yet in `npm`.  `npm` version still at 1.6.8

**Comment by laurenskling** [comment] 2021-08-06 18:23
Can we please have a release of the fix? 😅

**Comment by mdreizin** [comment] 2022-01-15 19:10
Do you still have that issue?

**Comment by mdreizin** [comment] 2022-01-15 19:21
Feel free to reopen that issue if you have that issue on Netlify.

**Closed by mdreizin** 2022-01-15 19:21 UTC
